frr version 10.6-dev_git20251028
frr defaults traditional
hostname frr3
log syslog informational
!
interface eth1
 ipv6 router isis CORE
 isis circuit-type level-2
exit
!
interface eth2
 ipv6 router isis CORE
 isis circuit-type level-2
exit
!
interface eth3
 ipv6 router isis CORE
 isis circuit-type level-2
exit
!
interface lo
 ipv6 router isis CORE
 isis circuit-type level-2
 isis passive
exit
!
router isis CORE
 is-type level-2
 net 49.0001.0001.0003.00
 lsp-mtu 1300
 redistribute ipv6 kernel level-2
 topology ipv6-unicast
 exit
exit
